interface ICountry {
  country: string;
  iso: string;
  format: string;
  regex: string;
}

const countryList: Array<ICountry> = [
  {
    country: 'Afghanistan',
    iso: 'AF',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Åland Islands',
    iso: 'AX',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Albania',
    iso: 'AL',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Algeria',
    iso: 'DZ',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Andorra',
    iso: 'AD',
    format: 'CCNNN',
    regex: '^[Aa][Dd]\\d{3}$',
  },
  {
    country: 'Angola',
    iso: 'AO',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Anguilla',
    iso: 'AI',
    format: 'AI-2640',
    regex: '^[Aa][I][-][2][6][4][0]$',
  },
  {
    country: 'Antigua and Barbuda',
    iso: 'AG',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Argentina',
    iso: 'AR',
    format: 'ANNNN(AAA)?',
    regex: '^[A-HJ-NP-Z]\\d{4}([A-Z]{3})?$',
  },
  {
    country: 'Armenia',
    iso: 'AM',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Aruba',
    iso: 'AW',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Australia',
    iso: 'AU',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Austria',
    iso: 'AT',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Azerbaijan',
    iso: 'AZ',
    format: 'CCNNNN',
    regex: '^[Aa][Zz]\\d{4}$',
  },
  {
    country: 'Bahamas',
    iso: 'BS',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Bahrain',
    iso: 'BH',
    format: 'NNN or NNNN',
    regex: '^\\d{3,4}$',
  },
  {
    country: 'Bangladesh',
    iso: 'BD',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Barbados',
    iso: 'BB',
    format: 'CCNNNNN',
    regex: '^BB*\\d{5}$',
  },
  {
    country: 'Belarus',
    iso: 'BY',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Belgium',
    iso: 'BE',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Belize',
    iso: 'BZ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Benin',
    iso: 'BJ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Bermuda',
    iso: 'BM',
    format: 'AA NN or AA AA',
    regex: '^[A-Za-z]{2} ([A-Za-z]{2}|\\d{2})$',
  },
  {
    country: 'Bhutan',
    iso: 'BT',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Bolivia',
    iso: 'BO',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Bonaire, Sint Eustatius and Saba',
    iso: 'BQ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Bosnia and Herzegovina',
    iso: 'BA',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Botswana',
    iso: 'BW',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Brazil',
    iso: 'BR',
    format: 'NNNNN-NNN',
    regex: '^\\d{5}-?\\d{3}$',
  },
  {
    country: 'British Virgin Islands',
    iso: 'VG',
    format: 'CCNNNN',
    regex: '^[Vv][Gg]\\d{4}$',
  },
  {
    country: 'Brunei',
    iso: 'BN',
    format: 'AANNNN',
    regex: '^[A-Za-z]{2}\\d{4}$',
  },
  {
    country: 'Bulgaria',
    iso: 'BG',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Burkina Faso',
    iso: 'BF',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Burundi',
    iso: 'BI',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Cambodia',
    iso: 'KH',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Cameroon',
    iso: 'CM',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Canada',
    iso: 'CA',
    format: 'ANA NAN',
    regex:
      '^[ABCEGHJKLMNPRSTVXYabceghjklmnprstvxy]\\d[ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz] ?\\d[ABCEGHJKLMNPRSTVWXYZabceghjklmnprstvwxyz]\\d$',
  },
  {
    country: 'Cape Verde',
    iso: 'CV',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Cayman Islands',
    iso: 'KY',
    format: 'CCN-NNNN',
    regex: '^[Kk][Yy]\\d[- ]?\\d{4}$',
  },
  {
    country: 'Central African Republic',
    iso: 'CF',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Chad',
    iso: 'TD',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Chile',
    iso: 'CL',
    format: 'NNNNNNN',
    regex: '^\\d{7}$',
  },
  {
    country: 'China',
    iso: 'CN',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Christmas Island',
    iso: 'CX',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Cocos (Keeling) Island',
    iso: 'CC',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Colombia',
    iso: 'CO',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Comoros',
    iso: 'KM',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Congo (Brazzaville)',
    iso: 'CG',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Congo, Democratic Republic',
    iso: 'CD',
    format: '- no codes -',
    regex: '^[Cc][Dd]$',
  },
  {
    country: 'Cook Islands',
    iso: 'CK',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Costa Rica',
    iso: 'CR',
    format: 'NNNNN (NNNN until 2007)',
    regex: '^\\d{4,5}$',
  },
  {
    country: "Côte d'Ivoire (Ivory Coast)",
    iso: 'CI',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Croatia',
    iso: 'HR',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Cuba',
    iso: 'CU',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Curaçao',
    iso: 'CW',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Cyprus',
    iso: 'CY',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Czech Republic',
    iso: 'CZ',
    format: 'NNN NN',
    regex: '^\\d{3} ?\\d{2}$',
  },
  {
    country: 'Denmark',
    iso: 'DK',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Djibouti',
    iso: 'DJ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Dominica',
    iso: 'DM',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Dominican Republic',
    iso: 'DO',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'East Timor',
    iso: 'TL',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Ecuador',
    iso: 'EC',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'El Salvador',
    iso: 'SV',
    format: '1101',
    regex: '^1101$',
  },
  {
    country: 'Egypt',
    iso: 'EG',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Equatorial Guinea',
    iso: 'GQ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Eritrea',
    iso: 'ER',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Estonia',
    iso: 'EE',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Ethiopia',
    iso: 'ET',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Faroe Islands',
    iso: 'FO',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'Fiji',
    iso: 'FJ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Finland',
    iso: 'FI',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'France',
    iso: 'FR',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'French Guiana',
    iso: 'GF',
    format: '973NN',
    regex: '^973\\d{2}$',
  },
  {
    country: 'French Polynesia',
    iso: 'PF',
    format: '987NN',
    regex: '^987\\d{2}$',
  },
  {
    country: 'French Southern and Antarctic Territories',
    iso: 'TF',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Gabon',
    iso: 'GA',
    format: 'NN [city name] NN',
    regex: '',
  },
  {
    country: 'Gambia',
    iso: 'GM',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Georgia',
    iso: 'GE',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Germany',
    iso: 'DE',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Ghana',
    iso: 'GH',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Gibraltar',
    iso: 'GI',
    format: 'GX11 1AA',
    regex: '^[Gg][Xx][1]{2} ?[1][Aa]{2}$',
  },
  {
    country: 'Greece',
    iso: 'GR',
    format: 'NNN NN',
    regex: '^\\d{3} ?\\d{2}$',
  },
  {
    country: 'Greenland',
    iso: 'GL',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Grenada',
    iso: 'GD',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Guadeloupe',
    iso: 'GP',
    format: '971NN',
    regex: '^971\\d{2}$',
  },
  {
    country: 'Guatemala',
    iso: 'GT',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Guernsey',
    iso: 'GG',
    format: 'AAN NAA, AANN NAA',
    regex: '^[A-Za-z]{2}\\d ?\\d[A-Za-z]{2}$',
  },
  {
    country: 'Guinea',
    iso: 'GN',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Guinea Bissau',
    iso: 'GW',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Guyana',
    iso: 'GY',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Haiti',
    iso: 'HT',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Heard and McDonald Islands',
    iso: 'HM',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Honduras',
    iso: 'HN',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Hong Kong',
    iso: 'HK',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Hungary',
    iso: 'HU',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Iceland',
    iso: 'IS',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'India',
    iso: 'IN',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Indonesia',
    iso: 'ID',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Iran',
    iso: 'IR',
    format: 'NNNNN-NNNNN',
    regex: '^\\d{5}(-?\\d{5})?$',
  },
  {
    country: 'Iraq',
    iso: 'IQ',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Ireland',
    iso: 'IE',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Isle of Man',
    iso: 'IM',
    format: 'CCN NAA, CCNN NAA',
    regex: '^[Ii][Mm]\\d{1,2} \\d[A-Z]{2}$',
  },
  {
    country: 'Israel',
    iso: 'IL',
    format: 'NNNNNNN',
    regex: '^\\d{7}$',
  },
  {
    country: 'Italy',
    iso: 'IT',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Jamaica',
    iso: 'JM',
    format: 'Before suspension: CCAAANN &#10;After suspension: NN',
    regex: '',
  },
  {
    country: 'Japan',
    iso: 'JP',
    format: 'NNN-NNNN',
    regex: '^\\d{3}-\\d{4}$',
  },
  {
    country: 'Jersey',
    iso: 'JE',
    format: 'CCN NAA',
    regex: '^[Jj][Ee]\\d ?\\d[A-Za-z]{2}$',
  },
  {
    country: 'Jordan',
    iso: 'JO',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Kazakhstan',
    iso: 'KZ',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Kenya',
    iso: 'KE',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Kiribati',
    iso: 'KI',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Korea, North',
    iso: 'KP',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Kosovo',
    iso: 'XK',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Kuwait',
    iso: 'KW',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Kyrgyzstan',
    iso: 'KG',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Latvia',
    iso: 'LV',
    format: 'LV-NNNN',
    regex: '^LV-\\d{4}$',
  },
  {
    country: 'Laos',
    iso: 'LA',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Lebanon',
    iso: 'LB',
    format: 'NNNN NNNN',
    regex: '^\\d{4}( \\d{4})?$',
  },
  {
    country: 'Lesotho',
    iso: 'LS',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'Liberia',
    iso: 'LR',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Libya',
    iso: 'LY',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Liechtenstein',
    iso: 'LI',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Lithuania',
    iso: 'LT',
    format: 'LT-NNNNN',
    regex: '^(LT-)?\\d{5}$',
  },
  {
    country: 'Luxembourg',
    iso: 'LU',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Macau',
    iso: 'MO',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Macedonia',
    iso: 'MK',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Madagascar',
    iso: 'MG',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'Malawi',
    iso: 'MW',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Maldives',
    iso: 'MV',
    format: 'NNNN, NNNNN',
    regex: '^\\d{4,5}$',
  },
  {
    country: 'Malaysia',
    iso: 'MY',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Mali',
    iso: 'ML',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Malta',
    iso: 'MT',
    format: 'AAA NNNN',
    regex: '^[A-Za-z]{3} ?\\d{4}$',
  },
  {
    country: 'Mauritania',
    iso: 'MR',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Mauritius',
    iso: 'MU',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Martinique',
    iso: 'MQ',
    format: '972NN',
    regex: '^972\\d{2}$',
  },
  {
    country: 'Mayotte',
    iso: 'YT',
    format: '976NN',
    regex: '^976\\d{2}$',
  },
  {
    country: 'Mexico',
    iso: 'MX',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Micronesia',
    iso: 'FM',
    format: '9694N',
    regex: '^9694\\d$',
  },
  {
    country: 'Moldova',
    iso: 'MD',
    format: 'MD-NNNN',
    regex: '^MD-\\d{4}$',
  },
  {
    country: 'Monaco',
    iso: 'MC',
    format: '980NN',
    regex: '^980\\d{2}$',
  },
  {
    country: 'Mongolia',
    iso: 'MN',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Montenegro',
    iso: 'ME',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Montserrat',
    iso: 'MS',
    format: 'MSR 1110-1350',
    regex: '^[Mm][Ss][Rr] ?\\d{4}$',
  },
  {
    country: 'Morocco',
    iso: 'MA',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Mozambique',
    iso: 'MZ',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Myanmar',
    iso: 'MM',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Namibia',
    iso: 'NA',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Nauru',
    iso: 'NR',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Nepal',
    iso: 'NP',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Netherlands',
    iso: 'NL',
    format: 'NNNN AA',
    regex: '^\\d{4} ?[A-Z]{2}$',
  },
  {
    country: 'New Caledonia',
    iso: 'NC',
    format: '988NN',
    regex: '^988\\d{2}$',
  },
  {
    country: 'New Zealand',
    iso: 'NZ',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Nicaragua',
    iso: 'NI',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Niger',
    iso: 'NE',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Nigeria',
    iso: 'NG',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Niue',
    iso: 'NU',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Norfolk Island',
    iso: 'NF',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Norway',
    iso: 'NO',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Oman',
    iso: 'OM',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'Pakistan',
    iso: 'PK',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Panama',
    iso: 'PA',
    format: 'NNNN',
    regex: '^(0\\d|10)\\d{2}$',
  },
  {
    country: 'Papua New Guinea',
    iso: 'PG',
    format: 'NNN',
    regex: '^\\d{3}$',
  },
  {
    country: 'Paraguay',
    iso: 'PY',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Peru',
    iso: 'PE',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Philippines',
    iso: 'PH',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Poland',
    iso: 'PL',
    format: 'NN-NNN',
    regex: '^\\d{2}[- ]?\\d{3}$',
  },
  {
    country: 'Portugal',
    iso: 'PT',
    format: 'NNNN-NNN',
    regex: '^\\d{4}[- ]?\\d{3}$',
  },
  {
    country: 'Qatar',
    iso: 'QA',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Réunion',
    iso: 'RE',
    format: '974NN',
    regex: '^974\\d{2}$',
  },
  {
    country: 'Romania',
    iso: 'RO',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Russia',
    iso: 'RU',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Saint Barthélemy',
    iso: 'BL',
    format: '97133',
    regex: '^97133$',
  },
  {
    country: 'Saint Kitts and Nevis',
    iso: 'KN',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Saint Lucia',
    iso: 'LC',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Saint Martin',
    iso: 'MF',
    format: '97150',
    regex: '^97150$',
  },
  {
    country: 'Saint Pierre and Miquelon',
    iso: 'PM',
    format: '97500',
    regex: '^97500$',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    iso: 'VC',
    format: 'CCNNNN',
    regex: '^[Vv][Cc]\\d{4}$',
  },
  {
    country: 'San Marino',
    iso: 'SM',
    format: '4789N',
    regex: '^4789\\d$',
  },
  {
    country: 'Sao Tome and Principe',
    iso: 'ST',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Saudi Arabia',
    iso: 'SA',
    format: 'NNNNN-NNNN',
    regex: '^\\d{5}(-\\d{4})?$',
  },
  {
    country: 'Senegal',
    iso: 'SN',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Serbia',
    iso: 'RS',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Seychelles',
    iso: 'SC',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Sint Maarten',
    iso: 'SX',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Sierra Leone',
    iso: 'SL',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Singapore',
    iso: 'SG',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Slovakia',
    iso: 'SK',
    format: 'NNN NN',
    regex: '^\\d{3} \\d{2}$',
  },
  {
    country: 'Slovenia',
    iso: 'SI',
    format: 'NNNN',
    regex: '^(SI-?)?\\d{4}$',
  },
  {
    country: 'Solomon Islands',
    iso: 'SB',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Somalia',
    iso: 'SO',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'South Africa',
    iso: 'ZA',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'South Korea',
    iso: 'KR',
    format: 'NNNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Spain',
    iso: 'ES',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Sri Lanka',
    iso: 'LK',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Sudan',
    iso: 'SD',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Suriname',
    iso: 'SR',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Swaziland',
    iso: 'SZ',
    format: 'ANNN',
    regex: '^[A-Za-z]\\d{3}$',
  },
  {
    country: 'Sweden',
    iso: 'SE',
    format: 'NNN NN',
    regex: '^(se-|SE-)?\\d{3} ?\\d{2}$',
  },
  {
    country: 'Switzerland',
    iso: 'CH',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Svalbard and Jan Mayen',
    iso: 'SJ',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Syria',
    iso: 'SY',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Taiwan',
    iso: 'TW',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Tajikistan',
    iso: 'TJ',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Tanzania',
    iso: 'TZ',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Thailand',
    iso: 'TH',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Togo',
    iso: 'TG',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Tokelau',
    iso: 'TK',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Tonga',
    iso: 'TO',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Trinidad and Tobago',
    iso: 'TT',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Tunisia',
    iso: 'TN',
    format: 'NNNN',
    regex: '^\\d{4}$',
  },
  {
    country: 'Turkey',
    iso: 'TR',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Turkmenistan',
    iso: 'TM',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Tuvalu',
    iso: 'TV',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Uganda',
    iso: 'UG',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Ukraine',
    iso: 'UA',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'United Arab Emirates',
    iso: 'AE',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'United Kingdom',
    iso: 'GB',
    format: 'A(A)N(A/N)NAA (A[A]N[A/N] NAA)',
    regex: '^[A-Za-z][A-Ha-hK-Yk-y]?\\d[A-Za-z0-9]? ?\\d[A-Za-z]{2}$',
  },
  {
    country: 'United States',
    iso: 'US',
    format: 'NNNNN-NNNN',
    regex: '^\\d{5}([- ]\\d{4})?$',
  },
  {
    country: 'Uruguay',
    iso: 'UY',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Uzbekistan',
    iso: 'UZ',
    format: 'NNN NNN',
    regex: '^\\d{3} \\d{3}$',
  },
  {
    country: 'Vanuatu',
    iso: 'VU',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Vatican',
    iso: 'VA',
    format: '120',
    regex: '^120$',
  },
  {
    country: 'Venezuela',
    iso: 'VE',
    format: 'NNNN A',
    regex: '^\\d{4}( [a-zA-Z])?$',
  },
  {
    country: 'Vietnam',
    iso: 'VN',
    format: 'NNNNNN',
    regex: '^\\d{6}$',
  },
  {
    country: 'Wallis and Futuna',
    iso: 'WF',
    format: '986NN',
    regex: '^986\\d{2}$',
  },
  {
    country: 'Yemen',
    iso: 'YE',
    format: '- no codes -',
    regex: '',
  },
  {
    country: 'Zambia',
    iso: 'ZM',
    format: 'NNNNN',
    regex: '^\\d{5}$',
  },
  {
    country: 'Zimbabwe',
    iso: 'ZW',
    format: '- no codes -',
    regex: '',
  },
];

export default countryList;
